### ISSUE TITLE
sqlite wants unicode strings [windows]

### ISSUE THREAD

**Issue by chadspratt** [chadspratt/AveryDB#66]
Traceback (most recent call last):
  File "gui_files.py", line 146, in changetarget
    self.initoutput(None)
  File "gui_fieldtoolbar.py", line 69, in initoutput
    self.processtasks(('sample', None))
  File "dbfutil.py", line 122, in processtasks
    self.converttosql(filealias, dataconverter)
  File "dbfutil.py", line 147, in converttosql
    for progress in dataconverter:
  File "table.py", line 71, in convertdata
    cur.execute(insertquery, values)
sqlite3.ProgrammingError: You must not use 8-bit bytestrings unless you use a text_factory that can interpret 8-bit bytestrings (like text_factory = str). It is highly recommended that you instead just switch your application to Unicode strings.

sigh

**Comment by chadspratt** [comment]
I've forgotten how to and can't reproduce this
e: just try loading a csv file
