### ISSUE TITLE
handle file in use for "Replace target"

### ISSUE THREAD

**Issue by chadspratt** [chadspratt/AveryDB#86]

**Comment by chadspratt** [comment]
Traceback (most recent call last):
  File "averydb.py", line 102, in queueexecution
    self.processtasks()
  File "backgroundtasks.py", line 51, in processtasks
    self.executejoin(None)
  File "averydb.py", line 186, in executejoin
    self.joins.targetdata.backup()
  File "filetypes\dbfdata.py", line 139, in backup
    os.rename(self.filename, backupname)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process
