### ISSUE TITLE
adjust field lengths after editing fields

### ISSUE THREAD

**Issue by chadspratt** [chadspratt/AveryDB#88]
renames the fields and crashes with 
Traceback (most recent call last):
  File "gui_fieldview.py", line 45, in autoadjustfieldlengths
    self.processtasks(('lengthadjust', lengthadjuster))
  File "backgroundtasks.py", line 39, in processtasks
    self.updatesample(taskdata)
  File "averydb.py", line 332, in updatesample
    self.gui['sampleoutputlist'].append(outputrecord)
ValueError: row sequence has wrong length

**Comment by chadspratt** [comment]
Haven't seen this error since fixing field renaming. don't see any relation though, so this may still be a problem
