### ISSUE TITLE
spaces in sheet names for excel files

### ISSUE THREAD

**Issue by chadspratt** [chadspratt/AveryDB#95]
```
Traceback (most recent call last):
  File "gui_files.py", line 178, in changetarget
    self.reloadfields(None)
  File "gui_fieldtoolbar.py", line 68, in reloadfields
    self.processtasks(('sample', 'refresh sample'))
  File "backgroundtasks.py", line 39, in processtasks
    self.updatesample(taskdata)
  File "averydb.py", line 305, in updatesample
    self.calc.createoutputfunc(self.outputs[fieldname])
  File "calculator.py", line 337, in createoutputfunc
    exec(newfuncstr) in tempcontext
  File "<string>", line 2
    return !countydataJM Query results.DISPLAY!
           ^
SyntaxError: invalid syntax
```

**Comment by chadspratt** [comment]
so the issue is that excel sheet names aren't getting aliased
